import = ["dracula.toml"]

[window]
option_as_alt = "OnlyLeft"

[font]
size = 14
offset = {x = 0, y = 8}

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "Backspace", mods = "Alt", chars = "\u001B\u007F" },  # Alt + Backspace (Delete word before cursor)
  { key = "Right", mods = "Alt", chars = "\u001BF" }, # Alt + arrow left/right move by word
  { key = "Left",  mods = "Alt", chars = "\u001BB" }
]
